// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyPlaceholderApiKeyForWebProject1048912133961',
    appId: '1:1048912133961:web:inteshar',
    messagingSenderId: '1048912133961',
    projectId: 'inteshar-1048912133961',
    authDomain: 'inteshar-1048912133961.firebaseapp.com',
    storageBucket: 'inteshar-1048912133961.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyPlaceholderApiKeyForAndroidProject1048912133961',
    appId: '1:1048912133961:android:com.dijlah.inteshar',
    messagingSenderId: '1048912133961',
    projectId: 'inteshar-1048912133961',
    storageBucket: 'inteshar-1048912133961.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyPlaceholderApiKeyForIosProject1048912133961',
    appId: '1:1048912133961:ios:com.dijlah.inteshar',
    messagingSenderId: '1048912133961',
    projectId: 'inteshar-1048912133961',
    storageBucket: 'inteshar-1048912133961.firebasestorage.app',
    iosBundleId: 'com.dijlah.inteshar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyPlaceholderApiKeyForMacosProject1048912133961',
    appId: '1:1048912133961:ios:com.dijlah.inteshar',
    messagingSenderId: '1048912133961',
    projectId: 'inteshar-1048912133961',
    storageBucket: 'inteshar-1048912133961.firebasestorage.app',
    iosBundleId: 'com.dijlah.inteshar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyPlaceholderApiKeyForWindowsProject1048912133961',
    appId: '1:1048912133961:web:inteshar',
    messagingSenderId: '1048912133961',
    projectId: 'inteshar-1048912133961',
    storageBucket: 'inteshar-1048912133961.firebasestorage.app',
  );
}
